In [1]:
import pandas as pd
import numpy as np

In [116]:
df = pd.read_csv("/content/drive/MyDrive/ AI ML/Colab Notebooks/train.csv")

In [117]:
df

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,Others,2024/07,High,NY,A,0.6429,False,False,True,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,Job_Title_1,2024/07,Low,CA,A,0.4678,False,False,False,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,Others,2024/07,Low,CA,A,0.4610,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,Others,2024/07,Low,CA,A,0.5064,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,Others,2024/07,Low,CA,A,0.4640,False,False,False,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,1276,Job_Title_21,2024/06,High,CA,A,0.5391,False,False,False,...,-0.089303,-0.471856,0.002497,0.245694,0.251105,0.119141,-0.184764,-0.482634,-0.819574,-0.241306
1276,1277,Others,2024/07,High,CA,A,0.7151,True,False,False,...,-0.079315,-0.796785,0.154025,-0.462344,-0.053803,-0.297083,-0.277624,-0.924568,-0.897608,-0.236864
1277,1278,Job_Title_10,2024/08,Medium,NY,A,0.5791,False,False,False,...,-0.030367,-0.329539,-0.429462,-0.141221,0.119336,-0.483549,-0.146601,-0.715821,-0.739832,-0.128655
1278,1279,Job_Title_2,2024/07,Medium,CA,A,0.7082,False,False,False,...,-0.213866,-0.242665,-0.311564,-0.032751,-0.301447,-0.480434,-0.112401,-0.828844,-1.066424,-0.228583
1279,1280,Job_Title_1,2024/07,Medium,NY,A,0.5997,False,False,True,...,-0.181357,-0.721596,-0.324486,-0.084486,-0.100463,-0.329224,-0.369456,-0.872554,-0.829080,-0.081490

In [118]:
df.head(10)

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,Others,2024/07,High,NY,A,0.6429,False,False,True,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,Job_Title_1,2024/07,Low,CA,A,0.4678,False,False,False,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,Others,2024/07,Low,CA,A,0.4610,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,Others,2024/07,Low,CA,A,0.5064,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,Others,2024/07,Low,CA,A,0.4640,False,False,False,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
5,6,Others,2024/01,High,WA,A,0.6681,False,False,False,...,-0.249678,-0.998258,-1.017181,0.372677,0.025714,-0.440318,-0.442595,-0.761192,-0.606944,-0.123160
6,7,Others,2024/07,Low,CA,A,0.4510,False,False,False,...,-0.158930,-0.684944,-0.484077,-0.289621,0.009149,-0.445414,-0.321164,-0.700979,-0.849695,0.004260
7,8,Others,2024/07,Low,NC,A,0.4661,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,9,Others,2024/07,High,CA,A,0.7349,False,False,False,...,-0.113091,-0.426043,-0.175965,-0.147661,0.197479,-0.207085,0.190253,-0.569806,-0.584224,0.143645
9,10,Others,2024/05,High,NY,A,0.7240,False,False,False,...,-0.649244,-0.323800,-0.138691,-0.478873,-0.115098,0.004634,-0.157343,-0.859955,-0.689171,0.005245

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Columns: 317 entries, obs to job_desc_300
dtypes: bool(9), float64(302), int64(1), object(5)
memory usage: 3.0+ MB

In [120]:
df.isnull().sum()

obs                 0
job_title           0
job_posted_date     1
salary_category     0
job_state          27
                   ..
job_desc_296        0
job_desc_297        0
job_desc_298        0
job_desc_299        0
job_desc_300        0
Length: 317, dtype: int64

In [121]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of        obs     job_title job_posted_date salary_category job_state feature_1  \
0        1        Others         2024/07            High        NY         A
1        2   Job_Title_1         2024/07             Low        CA         A
2        3        Others         2024/07             Low        CA         A
3        4        Others         2024/07             Low        CA         A
4        5        Others         2024/07             Low        CA         A
...    ...           ...             ...             ...       ...       ...
1275  1276  Job_Title_21         2024/06            High        CA         A
1276  1277        Others         2024/07            High        CA         A
1277  1278  Job_Title_10         2024/08          Medium        NY         A
1278  1279   Job_Title_2         2024/07          Medium        CA         A
1279  1280   Job_Title_1         2024/07          Medium        NY         A

      feature_2  feature_3  feature_4  feature_5  ...  job_desc_291  \
0        0.6429      False      False       True  ...     -0.362079
1        0.4678      False      False      False  ...     -0.300989
2        0.4610      False      False      False  ...      0.000000
3        0.5064      False      False      False  ...      0.000000
4        0.4640      False      False      False  ...     -0.406159
...         ...        ...        ...        ...  ...           ...
1275     0.5391      False      False      False  ...     -0.089303
1276     0.7151       True      False      False  ...     -0.079315
1277     0.5791      False      False      False  ...     -0.030367
1278     0.7082      False      False      False  ...     -0.213866
1279     0.5997      False      False       True  ...     -0.181357

      job_desc_292  job_desc_293  job_desc_294  job_desc_295  job_desc_296  \
0        -0.499308     -0.367894     -0.214881      0.014870     -0.271177
1        -0.415411     -0.341824     -0.319064      0.042322     -0.124755
2         0.000000      0.000000      0.000000      0.000000      0.000000
3         0.000000      0.000000      0.000000      0.000000      0.000000
4        -0.654657     -0.074398     -0.464479      0.081037     -0.136992
...            ...           ...           ...           ...           ...
1275     -0.471856      0.002497      0.245694      0.251105      0.119141
1276     -0.796785      0.154025     -0.462344     -0.053803     -0.297083
1277     -0.329539     -0.429462     -0.141221      0.119336     -0.483549
1278     -0.242665     -0.311564     -0.032751     -0.301447     -0.480434
1279     -0.721596     -0.324486     -0.084486     -0.100463     -0.329224

      job_desc_297  job_desc_298  job_desc_299  job_desc_300
0        -0.113347     -0.587955     -0.919095     -0.207340
1         0.023489     -0.893224     -0.823024      0.112364
2         0.000000      0.000000      0.000000      0.000000
3         0.000000      0.000000      0.000000      0.000000
4        -0.276270     -0.696853     -0.601466      0.089939
...            ...           ...           ...           ...
1275     -0.184764     -0.482634     -0.819574     -0.241306
1276     -0.277624     -0.924568     -0.897608     -0.236864
1277     -0.146601     -0.715821     -0.739832     -0.128655
1278     -0.112401     -0.828844     -1.066424     -0.228583
1279     -0.369456     -0.872554     -0.829080     -0.081490

[1280 rows x 317 columns]>

In [122]:
df.dropna( inplace = True)

In [123]:
df.feature_10.head(15)

0      60.0
1      60.0
2      36.0
3      72.0
4      48.0
5      36.0
6      60.0
7      60.0
8      72.0
12    180.0
13     24.0
14     60.0
15     96.0
16     12.0
17     60.0
Name: feature_10, dtype: float64

In [124]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [125]:
encoded_values = {'Low': 0, 'Medium': 1, 'High': 2}

df['salary_category'] = df['salary_category'].map(encoded_values)

In [126]:
df

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,Others,2024/07,2,NY,A,0.6429,False,False,True,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,Job_Title_1,2024/07,0,CA,A,0.4678,False,False,False,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,Others,2024/07,0,CA,A,0.4610,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,Others,2024/07,0,CA,A,0.5064,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,Others,2024/07,0,CA,A,0.4640,False,False,False,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1268,Others,2023/01,2,NY,A,0.5885,False,False,False,...,-0.490544,-0.671931,-0.057354,-0.649291,0.288155,-0.234996,-0.052687,-0.779074,-0.849742,0.460499
1268,1269,Others,2024/03,2,NY,A,0.7143,False,False,False,...,-0.326846,-0.545941,-0.467270,0.015498,0.166812,-0.457394,-0.006537,-0.521862,-0.571044,0.032121
1269,1270,Others,2024/07,0,CA,A,0.4586,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1272,1273,Others,2024/07,0,AL,A,0.4691,False,False,False,...,-1.066573,-1.031351,-0.366249,0.741466,-0.102016,0.132157,-0.205844,-0.724913,-0.477329,0.110609
1279,1280,Job_Title_1,2024/07,1,NY,A,0.5997,False,False,True,...,-0.181357,-0.721596,-0.324486,-0.084486,-0.100463,-0.329224,-0.369456,-0.872554,-0.829080,-0.081490

In [127]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in ['job_state', 'job_title', 'feature_1']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [128]:
df

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,26,2024/07,2,24,0,0.6429,False,False,True,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,0,2024/07,0,4,0,0.4678,False,False,False,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,26,2024/07,0,4,0,0.4610,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,26,2024/07,0,4,0,0.5064,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,26,2024/07,0,4,0,0.4640,False,False,False,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1268,26,2023/01,2,24,0,0.5885,False,False,False,...,-0.490544,-0.671931,-0.057354,-0.649291,0.288155,-0.234996,-0.052687,-0.779074,-0.849742,0.460499
1268,1269,26,2024/03,2,24,0,0.7143,False,False,False,...,-0.326846,-0.545941,-0.467270,0.015498,0.166812,-0.457394,-0.006537,-0.521862,-0.571044,0.032121
1269,1270,26,2024/07,0,4,0,0.4586,False,False,False,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1272,1273,26,2024/07,0,1,0,0.4691,False,False,False,...,-1.066573,-1.031351,-0.366249,0.741466,-0.102016,0.132157,-0.205844,-0.724913,-0.477329,0.110609
1279,1280,0,2024/07,1,24,0,0.5997,False,False,True,...,-0.181357,-0.721596,-0.324486,-0.084486,-0.100463,-0.329224,-0.369456,-0.872554,-0.829080,-0.081490

In [129]:
binary_columns = ['feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_11', 'feature_12']

# Convert True/False to 0/1
df[binary_columns] = df[binary_columns].astype(int)

In [130]:
df

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,26,2024/07,2,24,0,0.6429,0,0,1,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,0,2024/07,0,4,0,0.4678,0,0,0,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,26,2024/07,0,4,0,0.4610,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,26,2024/07,0,4,0,0.5064,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,26,2024/07,0,4,0,0.4640,0,0,0,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1268,26,2023/01,2,24,0,0.5885,0,0,0,...,-0.490544,-0.671931,-0.057354,-0.649291,0.288155,-0.234996,-0.052687,-0.779074,-0.849742,0.460499
1268,1269,26,2024/03,2,24,0,0.7143,0,0,0,...,-0.326846,-0.545941,-0.467270,0.015498,0.166812,-0.457394,-0.006537,-0.521862,-0.571044,0.032121
1269,1270,26,2024/07,0,4,0,0.4586,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1272,1273,26,2024/07,0,1,0,0.4691,0,0,0,...,-1.066573,-1.031351,-0.366249,0.741466,-0.102016,0.132157,-0.205844,-0.724913,-0.477329,0.110609
1279,1280,0,2024/07,1,24,0,0.5997,0,0,1,...,-0.181357,-0.721596,-0.324486,-0.084486,-0.100463,-0.329224,-0.369456,-0.872554,-0.829080,-0.081490

In [131]:
df

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,26,2024/07,2,24,0,0.6429,0,0,1,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,0,2024/07,0,4,0,0.4678,0,0,0,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,26,2024/07,0,4,0,0.4610,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,26,2024/07,0,4,0,0.5064,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,26,2024/07,0,4,0,0.4640,0,0,0,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1268,26,2023/01,2,24,0,0.5885,0,0,0,...,-0.490544,-0.671931,-0.057354,-0.649291,0.288155,-0.234996,-0.052687,-0.779074,-0.849742,0.460499
1268,1269,26,2024/03,2,24,0,0.7143,0,0,0,...,-0.326846,-0.545941,-0.467270,0.015498,0.166812,-0.457394,-0.006537,-0.521862,-0.571044,0.032121
1269,1270,26,2024/07,0,4,0,0.4586,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1272,1273,26,2024/07,0,1,0,0.4691,0,0,0,...,-1.066573,-1.031351,-0.366249,0.741466,-0.102016,0.132157,-0.205844,-0.724913,-0.477329,0.110609
1279,1280,0,2024/07,1,24,0,0.5997,0,0,1,...,-0.181357,-0.721596,-0.324486,-0.084486,-0.100463,-0.329224,-0.369456,-0.872554,-0.829080,-0.081490

In [17]:
#df = df.drop(  "obs", axis = 1)

In [ ]:
#df = df.drop(  "feature_1", axis = 1)

In [ ]:
#df = df.drop(  "feature_11", axis = 1)

In [132]:
# Extract the year as integer
df['job_posted_date'] = df['job_posted_date'].astype(str).str[:4].astype(int)

In [133]:
df

,obs,job_title,job_posted_date,salary_category,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1,26,2024,2,24,0,0.6429,0,0,1,...,-0.362079,-0.499308,-0.367894,-0.214881,0.014870,-0.271177,-0.113347,-0.587955,-0.919095,-0.207340
1,2,0,2024,0,4,0,0.4678,0,0,0,...,-0.300989,-0.415411,-0.341824,-0.319064,0.042322,-0.124755,0.023489,-0.893224,-0.823024,0.112364
2,3,26,2024,0,4,0,0.4610,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,4,26,2024,0,4,0,0.5064,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,26,2024,0,4,0,0.4640,0,0,0,...,-0.406159,-0.654657,-0.074398,-0.464479,0.081037,-0.136992,-0.276270,-0.696853,-0.601466,0.089939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1268,26,2023,2,24,0,0.5885,0,0,0,...,-0.490544,-0.671931,-0.057354,-0.649291,0.288155,-0.234996,-0.052687,-0.779074,-0.849742,0.460499
1268,1269,26,2024,2,24,0,0.7143,0,0,0,...,-0.326846,-0.545941,-0.467270,0.015498,0.166812,-0.457394,-0.006537,-0.521862,-0.571044,0.032121
1269,1270,26,2024,0,4,0,0.4586,0,0,0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1272,1273,26,2024,0,1,0,0.4691,0,0,0,...,-1.066573,-1.031351,-0.366249,0.741466,-0.102016,0.132157,-0.205844,-0.724913,-0.477329,0.110609
1279,1280,0,2024,1,24,0,0.5997,0,0,1,...,-0.181357,-0.721596,-0.324486,-0.084486,-0.100463,-0.329224,-0.369456,-0.872554,-0.829080,-0.081490

In [134]:
# Identify all job_desc columns dynamically
job_desc_columns = [col for col in df.columns if col.startswith('job_desc_')]

# Drop rows where any job_desc column has a 0
df = df[~(df[job_desc_columns] == 0).any(axis=1)]

In [135]:
df.feature_11

0       1
1       1
4       1
5       1
6       1
       ..
1266    1
1267    1
1268    1
1272    1
1279    1
Name: feature_11, Length: 720, dtype: int64

In [136]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['salary_category'])
y = df['salary_category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [137]:
print(X_train)

       obs  job_title  job_posted_date  job_state  feature_1  feature_2  \
711    712         26             2024         24          0     0.7307
65      66          0             2024         15          0     0.6279
191    192         26             2024          4          0     0.4688
1145  1146          1             2024         24          0     0.8117
96      97          0             2024         24          0     0.4262
...    ...        ...              ...        ...        ...        ...
123    124         26             2023         24          0     0.6181
188    189         26             2024         11          0     0.4640
497    498         26             2023          4          0     0.5942
786    787         24             2024          4          0     0.6238
181    182         26             2024          4          0     0.4525

      feature_3  feature_4  feature_5  feature_6  ...  job_desc_291  \
711           0          0          0          1  ...     -0.124723
65            0          0          1          0  ...     -0.172217
191           0          0          0          1  ...     -0.218293
1145          0          0          0          1  ...     -0.030458
96            1          0          0          1  ...     -0.491894
...         ...        ...        ...        ...  ...           ...
123           0          0          0          1  ...     -0.029900
188           0          0          0          1  ...     -0.081941
497           1          0          0          1  ...     -0.619531
786           1          0          0          1  ...     -0.297035
181           0          0          0          1  ...      0.167153

      job_desc_292  job_desc_293  job_desc_294  job_desc_295  job_desc_296  \
711      -0.303980     -0.367563     -0.493824      0.056324     -0.151211
65       -0.400429     -0.659490     -0.349565     -0.022740     -0.273369
191      -0.729124     -0.313110     -0.445791     -0.064149     -0.358276
1145     -0.272420     -0.371375     -0.285347     -0.032679     -0.457501
96       -0.677699     -0.306039     -0.147901      0.268784     -0.297662
...            ...           ...           ...           ...           ...
123      -0.466024     -0.130617     -0.577224      0.022699     -0.324900
188      -0.599430     -0.257135     -0.349993     -0.035233     -0.621948
497      -0.597634     -0.144592     -0.917560      0.130511     -0.268099
786      -0.560449     -0.437894     -0.320075      0.208582     -0.192580
181      -1.276467     -0.330368     -0.502022      0.099176     -0.626775

      job_desc_297  job_desc_298  job_desc_299  job_desc_300
711      -0.169818     -0.617983     -1.016583      0.003643
65       -0.217820     -0.539450     -0.905723     -0.111895
191      -0.100201     -0.880976     -1.064306     -0.204580
1145     -0.122744     -0.670333     -1.050766     -0.342058
96       -0.359555     -0.809435     -0.960386      0.054558
...            ...           ...           ...           ...
123      -0.143837     -0.743717     -0.808979     -0.106592
188      -0.193387     -0.498187     -0.717023     -0.133246
497      -0.098822     -0.894220     -1.079072      0.191050
786      -0.140307     -0.627346     -0.921586     -0.195830
181      -0.182438     -0.922217     -1.119192     -0.086272

[576 rows x 316 columns]

In [138]:
X_train.corr()

,obs,job_title,job_posted_date,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
obs,1.000000,0.002549,0.058984,-0.001969,-0.009880,0.034948,0.019746,0.064616,0.044650,-0.004354,...,-0.032106,0.012773,0.007829,0.034467,-0.054235,-0.000292,-0.040193,-0.038767,0.015978,0.059036
job_title,0.002549,1.000000,-0.086551,-0.054347,0.023802,0.040840,0.013615,-0.121572,-0.053309,-0.016093,...,-0.025508,-0.048224,-0.004201,0.020320,-0.028163,0.064435,0.015935,0.016311,0.073838,-0.055403
job_posted_date,0.058984,-0.086551,1.000000,0.000755,0.061461,-0.066706,0.016463,-0.040272,0.125090,-0.082450,...,0.009821,0.013682,-0.038378,0.004072,0.017370,0.012837,-0.030265,0.064047,-0.003309,-0.020788
job_state,-0.001969,-0.054347,0.000755,1.000000,0.050976,0.042780,0.040627,0.041998,0.039042,0.138449,...,-0.065976,0.060009,-0.050556,-0.019709,-0.007358,-0.066859,-0.003185,0.065985,-0.082031,-0.002943
feature_1,-0.009880,0.023802,0.061461,0.050976,1.000000,0.051197,0.095362,-0.030674,-0.018032,-0.041370,...,0.006049,-0.080031,-0.067198,0.081002,-0.011509,-0.027970,-0.072545,-0.063467,0.074855,-0.078180
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
job_desc_296,-0.000292,0.064435,0.012837,-0.066859,-0.027970,0.049717,-0.022176,-0.088420,0.128178,-0.021242,...,-0.070958,0.049403,0.253565,-0.088679,0.132915,1.000000,0.044811,0.027957,0.003937,-0.000832
job_desc_297,-0.040193,0.015935,-0.030265,-0.003185,-0.072545,0.059641,0.013138,-0.014664,-0.024414,0.060505,...,-0.053644,0.076123,0.099564,-0.037002,0.088833,0.044811,1.000000,-0.039270,-0.073993,0.148687
job_desc_298,-0.038767,0.016311,0.064047,0.065985,-0.063467,0.054843,-0.053846,0.055901,0.066055,0.072926,...,-0.220550,-0.129064,0.026515,0.197977,0.100996,0.027957,-0.039270,1.000000,0.041100,0.048373
job_desc_299,0.015978,0.073838,-0.003309,-0.082031,0.074855,-0.038659,0.004728,0.031627,-0.067091,-0.199248,...,-0.229345,-0.139905,0.019607,0.298962,0.032083,0.003937,-0.073993,0.041100,1.000000,0.076321
job_desc_300,0.059036,-0.055403,-0.020788,-0.002943,-0.078180,-0.028426,-0.008910,0.080227,0.017843,0.028397,...,-0.204056,-0.032301,0.090262,0.023333,0.035348,-0.000832,0.148687,0.048373,0.076321,1.000000

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize = (30,15))
sns.heatmap(X_train.corr(), annot = True, cmap=plt.cm.CMRmap_r)
plt.show

In [139]:
def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold: # we are interested in absolute coeff value
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)
    return col_corr

In [140]:
corr_features = correlation(X_train, 0.7)
len(set(corr_features))

1

In [141]:
X_train.drop(columns = corr_features)

,obs,job_title,job_posted_date,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
711,712,26,2024,24,0,0.7307,0,0,0,1,...,-0.124723,-0.303980,-0.367563,-0.493824,0.056324,-0.151211,-0.169818,-0.617983,-1.016583,0.003643
65,66,0,2024,15,0,0.6279,0,0,1,0,...,-0.172217,-0.400429,-0.659490,-0.349565,-0.022740,-0.273369,-0.217820,-0.539450,-0.905723,-0.111895
191,192,26,2024,4,0,0.4688,0,0,0,1,...,-0.218293,-0.729124,-0.313110,-0.445791,-0.064149,-0.358276,-0.100201,-0.880976,-1.064306,-0.204580
1145,1146,1,2024,24,0,0.8117,0,0,0,1,...,-0.030458,-0.272420,-0.371375,-0.285347,-0.032679,-0.457501,-0.122744,-0.670333,-1.050766,-0.342058
96,97,0,2024,24,0,0.4262,1,0,0,1,...,-0.491894,-0.677699,-0.306039,-0.147901,0.268784,-0.297662,-0.359555,-0.809435,-0.960386,0.054558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,26,2023,24,0,0.6181,0,0,0,1,...,-0.029900,-0.466024,-0.130617,-0.577224,0.022699,-0.324900,-0.143837,-0.743717,-0.808979,-0.106592
188,189,26,2024,11,0,0.4640,0,0,0,1,...,-0.081941,-0.599430,-0.257135,-0.349993,-0.035233,-0.621948,-0.193387,-0.498187,-0.717023,-0.133246
497,498,26,2023,4,0,0.5942,1,0,0,1,...,-0.619531,-0.597634,-0.144592,-0.917560,0.130511,-0.268099,-0.098822,-0.894220,-1.079072,0.191050
786,787,24,2024,4,0,0.6238,1,0,0,1,...,-0.297035,-0.560449,-0.437894,-0.320075,0.208582,-0.192580,-0.140307,-0.627346,-0.921586,-0.195830
181,182,26,2024,4,0,0.4525,0,0,0,1,...,0.167153,-1.276467,-0.330368,-0.502022,0.099176,-0.626775,-0.182438,-0.922217,-1.119192,-0.086272

In [142]:
y_train.head(10)

711     2
65      0
191     0
1145    2
96      1
290     2
842     2
592     2
958     0
37      1
Name: salary_category, dtype: int64

In [143]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=42)
xgb_model.fit(X_train, y_train)
y_pred_xgb = xgb_model.predict(X_test)

print(f"XGBoost Accuracy: {accuracy_score(y_test, y_pred_xgb):.2f}")

XGBoost Accuracy: 0.72

In [144]:
# Train Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print(f"Random Forest Accuracy: {accuracy_score(y_test, y_pred_rf):.2f}")

Random Forest Accuracy: 0.64

In [145]:
test_df = pd.read_csv("/content/drive/MyDrive/ AI ML/Colab Notebooks/test.csv")

In [146]:
test_df

,obs,job_title,job_posted_date,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1281,Others,2024/06,CA,A,0.6473,False,False,True,True,...,-0.054078,-0.573635,-0.306883,-0.325092,0.089463,-0.353476,-0.159314,-0.667958,-0.702116,-0.206267
1,1282,Others,2024/08,NY,A,0.4238,True,False,False,False,...,-0.868718,-0.337967,-0.179036,-0.717763,0.404843,0.032468,-0.190448,-1.261702,-0.505897,0.082080
2,1283,Others,2023/01,CA,A,0.6219,True,False,False,True,...,-0.416109,-0.619822,-0.493653,-0.347556,0.071679,-0.331212,-0.381348,-0.506540,-0.773561,-0.105221
3,1284,Job_Title_5,2024/06,NY,A,0.6704,False,False,False,True,...,-0.297560,-0.481448,-0.497642,-0.254823,0.047404,-0.362739,-0.102704,-0.491272,-0.808156,-0.048326
4,1285,Others,2024/05,CA,A,0.7310,False,False,False,True,...,-0.176458,-0.726473,-0.323976,-0.145825,-0.046866,-0.229873,-0.568318,-0.614605,-0.770506,0.142140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
849,2130,Others,2024/06,CA,A,0.7444,False,False,False,True,...,-0.374370,-0.576530,-0.999262,-0.171388,0.090702,-0.497702,-0.053744,-0.819891,-0.692933,0.007312
850,2131,Others,2024/02,CA,A,0.6843,False,False,False,True,...,-0.143645,-0.660916,-0.764757,-0.593790,0.263615,-0.947461,-0.024984,-0.643991,-1.211826,0.069475
851,2132,Job_Title_3,2024/06,IL,A,0.8595,False,False,False,True,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
852,2133,Job_Title_3,2024/06,DC,A,0.9003,False,False,False,True,...,0.027034,-0.755793,-0.754356,0.105230,0.147808,-0.789086,0.006530,-0.618902,-0.887332,-0.082897
853,2134,Job_Title_16,2024/06,CA,A,0.7344,False,False,False,True,...,-0.840198,-1.307757,-0.415923,-0.228817,0.492109,-0.016296,-0.391734,-0.707052,-0.369870,0.404236

In [147]:
 # Extract the year as integer
test_df['job_posted_date'] = test_df['job_posted_date'].astype(str).str[:4].astype(int)

In [148]:
# Identify all job_desc columns dynamically
job_desc_columns = [col for col in test_df.columns if col.startswith('job_desc_')]

# Drop rows where any job_desc column has a 0
test_df = test_df[~(test_df[job_desc_columns] == 0).any(axis=1)]

In [149]:
test_df

,obs,job_title,job_posted_date,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1281,Others,2024,CA,A,0.6473,False,False,True,True,...,-0.054078,-0.573635,-0.306883,-0.325092,0.089463,-0.353476,-0.159314,-0.667958,-0.702116,-0.206267
1,1282,Others,2024,NY,A,0.4238,True,False,False,False,...,-0.868718,-0.337967,-0.179036,-0.717763,0.404843,0.032468,-0.190448,-1.261702,-0.505897,0.082080
2,1283,Others,2023,CA,A,0.6219,True,False,False,True,...,-0.416109,-0.619822,-0.493653,-0.347556,0.071679,-0.331212,-0.381348,-0.506540,-0.773561,-0.105221
3,1284,Job_Title_5,2024,NY,A,0.6704,False,False,False,True,...,-0.297560,-0.481448,-0.497642,-0.254823,0.047404,-0.362739,-0.102704,-0.491272,-0.808156,-0.048326
4,1285,Others,2024,CA,A,0.7310,False,False,False,True,...,-0.176458,-0.726473,-0.323976,-0.145825,-0.046866,-0.229873,-0.568318,-0.614605,-0.770506,0.142140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,2129,Others,2023,NY,A,0.5306,False,True,False,False,...,-0.684357,-0.616607,-0.423538,-0.310595,-0.052966,-0.512545,-0.064995,-0.641291,-0.804247,-0.074817
849,2130,Others,2024,CA,A,0.7444,False,False,False,True,...,-0.374370,-0.576530,-0.999262,-0.171388,0.090702,-0.497702,-0.053744,-0.819891,-0.692933,0.007312
850,2131,Others,2024,CA,A,0.6843,False,False,False,True,...,-0.143645,-0.660916,-0.764757,-0.593790,0.263615,-0.947461,-0.024984,-0.643991,-1.211826,0.069475
852,2133,Job_Title_3,2024,DC,A,0.9003,False,False,False,True,...,0.027034,-0.755793,-0.754356,0.105230,0.147808,-0.789086,0.006530,-0.618902,-0.887332,-0.082897
853,2134,Job_Title_16,2024,CA,A,0.7344,False,False,False,True,...,-0.840198,-1.307757,-0.415923,-0.228817,0.492109,-0.016296,-0.391734,-0.707052,-0.369870,0.404236

In [150]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for col in ['job_state', 'job_title', 'feature_1']:
    le = LabelEncoder()
    test_df[col] = le.fit_transform(test_df[col])
    label_encoders[col] = le

<ipython-input-150-5bb863c5583f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[col] = le.fit_transform(test_df[col])
<ipython-input-150-5bb863c5583f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[col] = le.fit_transform(test_df[col])
<ipython-input-150-5bb863c5583f>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[col] = le.fit_transform(test_df[col])

In [151]:
test_df

,obs,job_title,job_posted_date,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1281,26,2024,3,0,0.6473,False,False,True,True,...,-0.054078,-0.573635,-0.306883,-0.325092,0.089463,-0.353476,-0.159314,-0.667958,-0.702116,-0.206267
1,1282,26,2024,22,0,0.4238,True,False,False,False,...,-0.868718,-0.337967,-0.179036,-0.717763,0.404843,0.032468,-0.190448,-1.261702,-0.505897,0.082080
2,1283,26,2023,3,0,0.6219,True,False,False,True,...,-0.416109,-0.619822,-0.493653,-0.347556,0.071679,-0.331212,-0.381348,-0.506540,-0.773561,-0.105221
3,1284,21,2024,22,0,0.6704,False,False,False,True,...,-0.297560,-0.481448,-0.497642,-0.254823,0.047404,-0.362739,-0.102704,-0.491272,-0.808156,-0.048326
4,1285,26,2024,3,0,0.7310,False,False,False,True,...,-0.176458,-0.726473,-0.323976,-0.145825,-0.046866,-0.229873,-0.568318,-0.614605,-0.770506,0.142140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,2129,26,2023,22,0,0.5306,False,True,False,False,...,-0.684357,-0.616607,-0.423538,-0.310595,-0.052966,-0.512545,-0.064995,-0.641291,-0.804247,-0.074817
849,2130,26,2024,3,0,0.7444,False,False,False,True,...,-0.374370,-0.576530,-0.999262,-0.171388,0.090702,-0.497702,-0.053744,-0.819891,-0.692933,0.007312
850,2131,26,2024,3,0,0.6843,False,False,False,True,...,-0.143645,-0.660916,-0.764757,-0.593790,0.263615,-0.947461,-0.024984,-0.643991,-1.211826,0.069475
852,2133,19,2024,6,0,0.9003,False,False,False,True,...,0.027034,-0.755793,-0.754356,0.105230,0.147808,-0.789086,0.006530,-0.618902,-0.887332,-0.082897
853,2134,7,2024,3,0,0.7344,False,False,False,True,...,-0.840198,-1.307757,-0.415923,-0.228817,0.492109,-0.016296,-0.391734,-0.707052,-0.369870,0.404236

In [155]:
binary_columns = ['feature_3', 'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_11','feature_12']

# Convert True/False to 0/1
test_df[binary_columns] = test_df[binary_columns].astype(int)

<ipython-input-155-ad59ef8fd8ae>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df[binary_columns] = test_df[binary_columns].astype(int)

In [156]:
test_df

,obs,job_title,job_posted_date,job_state,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,...,job_desc_291,job_desc_292,job_desc_293,job_desc_294,job_desc_295,job_desc_296,job_desc_297,job_desc_298,job_desc_299,job_desc_300
0,1281,26,2024,3,0,0.6473,0,0,1,1,...,-0.054078,-0.573635,-0.306883,-0.325092,0.089463,-0.353476,-0.159314,-0.667958,-0.702116,-0.206267
1,1282,26,2024,22,0,0.4238,1,0,0,0,...,-0.868718,-0.337967,-0.179036,-0.717763,0.404843,0.032468,-0.190448,-1.261702,-0.505897,0.082080
2,1283,26,2023,3,0,0.6219,1,0,0,1,...,-0.416109,-0.619822,-0.493653,-0.347556,0.071679,-0.331212,-0.381348,-0.506540,-0.773561,-0.105221
3,1284,21,2024,22,0,0.6704,0,0,0,1,...,-0.297560,-0.481448,-0.497642,-0.254823,0.047404,-0.362739,-0.102704,-0.491272,-0.808156,-0.048326
4,1285,26,2024,3,0,0.7310,0,0,0,1,...,-0.176458,-0.726473,-0.323976,-0.145825,-0.046866,-0.229873,-0.568318,-0.614605,-0.770506,0.142140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,2129,26,2023,22,0,0.5306,0,1,0,0,...,-0.684357,-0.616607,-0.423538,-0.310595,-0.052966,-0.512545,-0.064995,-0.641291,-0.804247,-0.074817
849,2130,26,2024,3,0,0.7444,0,0,0,1,...,-0.374370,-0.576530,-0.999262,-0.171388,0.090702,-0.497702,-0.053744,-0.819891,-0.692933,0.007312
850,2131,26,2024,3,0,0.6843,0,0,0,1,...,-0.143645,-0.660916,-0.764757,-0.593790,0.263615,-0.947461,-0.024984,-0.643991,-1.211826,0.069475
852,2133,19,2024,6,0,0.9003,0,0,0,1,...,0.027034,-0.755793,-0.754356,0.105230,0.147808,-0.789086,0.006530,-0.618902,-0.887332,-0.082897
853,2134,7,2024,3,0,0.7344,0,0,0,1,...,-0.840198,-1.307757,-0.415923,-0.228817,0.492109,-0.016296,-0.391734,-0.707052,-0.369870,0.404236

In [157]:
y_pred_xgb = xgb_model.predict(test_df)

#print(f"XGBoost Accuracy: {accuracy_score(y_test, y_pred_xgb):.2f}")

In [167]:
print(y_pred_xgb)

[2 1 2 0 2 2 2 0 1 1 1 2 0 0 0 2 2 2 2 2 1 2 0 2 2 0 0 2 2 0 0 1 1 1 0 1 0
 1 1 0 2 0 2 1 2 0 0 2 2 0 2 1 2 2 2 1 2 2 1 1 1 2 2 2 2 2 2 1 0 1 1 0 2 2
 1 2 2 2 2 1 2 2 0 1 0 1 2 2 1 2 1 2 2 2 1 0 0 1 2 2 0 1 2 2 2 2 2 2 0 1 0
 0 0 1 2 1 0 2 0 1 2 2 2 2 0 2 0 2 2 2 2 2 2 0 2 1 1 2 2 0 1 0 0 2 2 1 2 2
 2 2 2 2 0 1 1 1 0 1 2 1 2 0 2 0 1 2 1 1 0 1 0 1 1 2 2 1 1 1 1 2 2 2 0 1 1
 0 1 0 2 1 2 2 0 1 0 2 1 1 1 2 0 2 0 0 2 1 2 2 1 2 2 2 2 2 2 0 1 2 1 1 2 0
 2 2 2 2 0 0 2 2 2 1 2 0 2 2 0 0 1 0 1 2 2 1 1 0 2 0 2 0 2 0 2 2 0 0 2 1 1
 2 2 2 2 2 0 0 2 0 1 2 0 2 2 2 2 0 2 2 0 1 2 0 1 1 1 1 1 2 2 2 1 2 0 2 1 2
 2 1 0 0 2 2 1 1 2 0 0 2 0 2 2 2 0 2 2 2 1 2 1 1 2 2 0 1 2 2 2 2 2 0 2 2 2
 1 2 0 1 0 2 2 2 0 2 2 2 2 1 2 1 2 1 0 0 1 1 1 1 0 2 0 2 0 2 2 0 2 0 2 2 0
 2 1 1 2 2 1 2 2 2 2 2 1 2 2 1 2 2 1 2 2 0 2 0 2 2 1 2 2 0 2 1 2 2 1 2 2 2
 2 2 2 2 1 2 0 2 2 2 1 1 0 1 1 1 2 2 1 2 2 2 2 0 0 0 2 1 0 2 2 1 2 1 0 0 2
 2 2 0 1 0 0 0 2 2 0 1 2 0 2 0 0 2 0 2 1 1 2 0 2 1 2 0 1 0 2 2 2 0 0 2 1 0
 0 1 1 2 2 2 1 1 0 2 0 1 1 0 1 2 2 1 0 2 0 0 2 0 2 1 0 2 2 2 0 2 1 1 1 2 0
 0 2 2 2 0 2 0 2 1 0 1 0 2 2 2 0 0 1 2 0 2 1 0 2 0 0 0 2 1 1 1 2 1 1 1 2 0
 2 0 2 2 0 2 2 1 1 2 2 2 2 0 0 0 2 1 2 2 0 2 2 2 2 2 1 2 0 2 1 0 2 2 0 2 0
 2 0 0 1 0 2 2 2 0 2 2 2 2 2 2 0 2 0 2 1 1 1 0 1 1 2 2 0 1 0 1 1 2 1 0 0 1
 2 2 1 1 0 2 1 2 2 2 0 2 2 1 2 0 2 1 1 1 2 0 0 2 1 2 0 1 2 2 1 2 2 0 2 1 0
 1 1 0 2 0 2 1 0 2 2 2 0 2 2 2 2 2 2 2 1 2 0 2 2 2 2 2 2 2 1 2 2 1 1 2 0 1
 2 0 0 2 2 1 1 2 2 1 1 0 2 0 2 2 2 0 2 2 2 2 2 2 1 2 2 0 1 1 2 1 2 1 1 2 1
 0 2]

In [178]:
label_map = {0: 'Low', 1: 'Medium', 2: 'High'}
y_pred_labels = [label_map[pred] for pred in y_pred_xgb]

In [179]:

# If 'obs_id' exists
submission_df = pd.DataFrame({
    'obs': test_df['obs'],  # or 'id' or any identifier column
    'salary_category': y_pred_labels
})

# If there's no identifier column, just use the index
# submission_df = pd.DataFrame({
#     'obs_id': test_df.index,
#     'salary': y_pred_labels
# })

In [180]:
print(submission_df)

      obs salary_category
0    1281            High
1    1282          Medium
2    1283            High
3    1284             Low
4    1285            High
..    ...             ...
848  2129          Medium
849  2130            High
850  2131          Medium
852  2133             Low
853  2134            High

[742 rows x 2 columns]

In [181]:
submission_df.to_csv('solution_format.csv', index=False)

In [182]:
from google.colab import files
files.download('solution_format.csv')